// ===== WUNDERKART DATA =====
export const PHRASES = {
  start: ["Let's go!", "Full throttle!", "Let's move!", "Here we go!", "Ready, set, go!"],
  boost: ["Wonderful!", "Woohoo!", "Turbo!", "Let's roll!", "Full throttle!", "Nice!"],
  trick: ["Yes!", "Whee!", "Excellent!", "What a jump!", "Fantastic!", "Hop!"],
  hit: ["Darn!", "Oh no!", "Wow!", "Darn it!", "Ouch!", "For crying out loud!", "Just great!", "What nonsense!"],
  hitOther: ["Ha! Got you!", "Bye!", "See you later!", "Bless you!", "I meant to do that!", "Too bad!"],
  pass: ["Make way!", "Out of the way!", "Passed you!", "Bye-bye!", "Too slow!"],
  fall: ["Whoops!", "Noooo!", "I'm flying!", "Help!", "Oh no!"],
  item: ["Ooh!", "There we go!", "Perfect!", "Hehehe…"],
  wall: ["Whoa!", "Phew!", "The wall!"],
  win: ["World Champion!", "First! Of course!", "Order must be kept!", "Victory!"],
  lose: ["Next time…", "That was unfair!", "I protest!", "What a shame!"],
  big: ["AAAAAAAH!", "INSANE!", "Oh my gosh!", "Mom!", "Whoa!", "Watch out!!"],
};

export const CHARACTERS = [
  { id:"beethoven", name:"Ludwig van Beethoven", short:"Beethoven", cls:"Heavy", spd:4, acc:2, hnd:2, wt:5,
    look:{hair:"wild", hc:0x55504a, suit:0x2a2a3a, kart:0x1d2b53, acc2:0xffd23f},
    ability:{name:"Fate Symphony", type:"shield", desc:"Immune to knockback during a dramatic music cue."},
    lines:["Da-da-da-DAAA!", "I can't hear anything!", "Ode to Joy!"] },
  { id:"goethe", name:"Johann Wolfgang von Goethe", short:"Goethe", cls:"Balanced", spd:3, acc:3, hnd:3, wt:3,
    look:{hair:"side", hc:0x6b4a2b, suit:0x6a1b2a, kart:0x8b1e3f, acc2:0xf2c14e},
    ability:{name:"Faustian Bargain", type:"faust", desc:"Risky shortcut: warps you ahead… usually."},
    lines:["More light!", "Stay awhile!", "A deal with the devil!"] },
  { id:"bach", name:"Johann Sebastian Bach", short:"Bach", cls:"Technical", spd:3, acc:3, hnd:4, wt:3,
    look:{hair:"wig", hc:0xf2f2f2, suit:0x3b2f63, kart:0x6c4ab6, acc2:0xffffff},
    ability:{name:"Fugue", type:"notes", desc:"Drops bouncing musical notes behind."},
    lines:["Toccata!", "Fugue in D minor!", "Counterpoint!"] },
  { id:"wagner", name:"Richard Wagner", short:"Wagner", cls:"Heavy", spd:4, acc:2, hnd:2, wt:5,
    look:{hair:"beret", hc:0x8a7a6a, suit:0x1a1a1a, kart:0x7a0c0c, acc2:0xd4af37},
    ability:{name:"Ride of the Valkyries", type:"bigboost", desc:"Orchestral buildup → MASSIVE acceleration."},
    lines:["Ride!", "Valhalla!", "The total work of art!"] },
  { id:"clara", name:"Clara Schumann", short:"Clara", cls:"Technical", spd:3, acc:4, hnd:4, wt:2,
    look:{hair:"bun", hc:0x3b2416, suit:0x2f5d50, kart:0x3aa17e, acc2:0xf5e6c8},
    ability:{name:"Precision", type:"drift", desc:"Drift charges twice as fast for a while."},
    lines:["Precise!", "Played perfectly!", "Allegro!"] },
  { id:"marlene", name:"Marlene Dietrich", short:"Marlene", cls:"Light", spd:3, acc:5, hnd:4, wt:1,
    look:{hair:"tophat", hc:0xf0d08a, suit:0x111111, kart:0xe6e6e6, acc2:0xc9a227},
    ability:{name:"Doppelganger", type:"decoy", desc:"Spawns a decoy kart that eats hits."},
    lines:["From head to toe…", "Darling!", "Lili Marlene!"] },
  { id:"grimm", name:"Brothers Grimm", short:"Grimm", cls:"Duo", spd:3, acc:3, hnd:3, wt:4,
    look:{hair:"duo", hc:0x4a3020, suit:0x3d4f2a, kart:0x5a7d2a, acc2:0xe8c170},
    ability:{name:"Once upon a time…", type:"fairy", desc:"Summons a random fairy-tale event."},
    lines:["Once upon a time!", "Rumpelstiltskin!", "Mirror, mirror!"] },
  { id:"einstein", name:"Albert Einstein", short:"Einstein", cls:"Medium", spd:3, acc:3, hnd:3, wt:3,
    look:{hair:"einstein", hc:0xffffff, suit:0x6d6457, kart:0xf08a24, acc2:0xffffff},
    ability:{name:"Relativity", type:"slowworld", desc:"Slows everyone else down."},
    lines:["Everything is relative!", "E equals M C squared!", "God does not play dice!"] },
  { id:"kbenz", name:"Karl Benz", short:"Karl Benz", cls:"Speed", spd:5, acc:2, hnd:3, wt:3,
    look:{hair:"beard", hc:0x6b6b6b, suit:0x2b2b2b, kart:0xb8b8c0, acc2:0x222222},
    ability:{name:"Patent Motorcar", type:"topspeed", desc:"Huge top-speed boost."},
    lines:["The automobile!", "More horsepower!", "I invented it!"] },
  { id:"bbenz", name:"Bertha Benz", short:"Bertha", cls:"Speed", spd:5, acc:3, hnd:3, wt:2,
    look:{hair:"bun", hc:0x2b1a10, suit:0x5a2d5a, kart:0xd94f8a, acc2:0xffffff},
    ability:{name:"First Long-Distance Drive", type:"pads", desc:"Boost pads & shortcuts give double power."},
    lines:["I'll drive myself!", "To Pforzheim!", "Men!"] },
  { id:"humboldt", name:"Alexander von Humboldt", short:"Humboldt", cls:"Explorer", spd:3, acc:4, hnd:3, wt:2,
    look:{hair:"side", hc:0x7a5a3a, suit:0x5c4a2a, kart:0x2e8b57, acc2:0xd2b48c},
    ability:{name:"Cosmos", type:"explore", desc:"Discovers a new item + a speed burst."},
    lines:["Everything is connected!", "A new path!", "The cosmos!"] },
  { id:"koch", name:"Robert Koch", short:"Koch", cls:"Technical", spd:3, acc:3, hnd:4, wt:3,
    look:{hair:"beard", hc:0x9a9a9a, suit:0xeeeeee, kart:0x88c057, acc2:0x1b5e20},
    ability:{name:"Lab Zone", type:"cloud", desc:"Leaves a germ cloud that slows others."},
    lines:["Germs!", "Disinfect!", "Wash your hands!"] },
  { id:"rontgen", name:"Wilhelm Röntgen", short:"Röntgen", cls:"Oddball", spd:3, acc:3, hnd:3, wt:3,
    look:{hair:"beard", hc:0x3a2a1a, suit:0x203040, kart:0x00c8ff, acc2:0x00ffcc},
    ability:{name:"X-Ray Vision", type:"phase", desc:"Turns ghostly: phase through hazards & hits."},
    lines:["I can see everything!", "X-rayed!", "X-rays!"] },
  { id:"planck", name:"Max Planck", short:"Planck", cls:"Technical", spd:3, acc:4, hnd:3, wt:3,
    look:{hair:"bald", hc:0x777777, suit:0x2d3047, kart:0x4361ee, acc2:0xffd60a},
    ability:{name:"Quantum Theory", type:"multiboost", desc:"Splits a boost into 5 quantum bursts."},
    lines:["Quantum leap!", "H times nu!", "Discrete!"] },
  { id:"noether", name:"Emmy Noether", short:"Noether", cls:"Pro", spd:4, acc:3, hnd:4, wt:2,
    look:{hair:"short", hc:0x2a1a12, suit:0x3a3a5a, kart:0x9b5de5, acc2:0xf15bb5},
    ability:{name:"Conservation Law", type:"momentum", desc:"Boost scales with your current speed."},
    lines:["Symmetry!", "Conservation of momentum!", "Elegant!"] },
  { id:"diesel", name:"Rudolf Diesel", short:"Diesel", cls:"Heavy", spd:4, acc:5, hnd:1, wt:5,
    look:{hair:"beard", hc:0x4a3a2a, suit:0x3a3a3a, kart:0x555555, acc2:0xff6b00},
    ability:{name:"Smoke Cloud", type:"smoke", desc:"Huge boost + smoke cloud behind."},
    lines:["Vroom vroom!", "Self-ignition!", "More torque!"] },
  { id:"bosch", name:"Robert Bosch", short:"Bosch", cls:"Balanced", spd:3, acc:3, hnd:3, wt:3,
    look:{hair:"beard", hc:0xdddddd, suit:0x003366, kart:0xc8102e, acc2:0xffffff},
    ability:{name:"Engineer Mode", type:"recover", desc:"Auto-recovers from the next hit with a boost."},
    lines:["Quality!", "Spark plug!", "Precision work!"] },
  { id:"zuse", name:"Konrad Zuse", short:"Zuse", cls:"Technical", spd:3, acc:3, hnd:4, wt:3,
    look:{hair:"short", hc:0x3a2a1a, suit:0x445544, kart:0x00a86b, acc2:0x00ff00},
    ability:{name:"Z3 Calculation", type:"deflect", desc:"Predicts & deflects incoming items."},
    lines:["One zero one!", "Calculated!", "Program running!"] },
  { id:"schumi", name:"Michael Schumacher", short:"Schumi", cls:"Speed", spd:5, acc:4, hnd:5, wt:3,
    look:{hair:"helmet", hc:0xdd0000, suit:0xdd0000, kart:0xff1e1e, acc2:0xffe600},
    ability:{name:"Rain Master", type:"driftchain", desc:"Drift chains give escalating boosts."},
    lines:["World Champion!", "Racing line!", "No problem!"] },
  { id:"graf", name:"Steffi Graf", short:"Steffi", cls:"Technical", spd:3, acc:4, hnd:5, wt:2,
    look:{hair:"ponytail", hc:0xc9a35a, suit:0xffffff, kart:0xfafafa, acc2:0x2a9d8f},
    ability:{name:"Golden Slam", type:"serve", desc:"Serves 3 tennis balls forward."},
    lines:["Ace!", "Game, set, victory!", "Serve!"] },
  { id:"kaiser", name:"Franz Beckenbauer", short:"Kaiser", cls:"Balanced", spd:3, acc:3, hnd:3, wt:3,
    look:{hair:"short", hc:0x8a6a3a, suit:0xffffff, kart:0xe0e0e0, acc2:0x000000},
    ability:{name:"Libero", type:"kick", desc:"Kicks a football that bounces off walls."},
    lines:["Let's see!", "Goal!", "Well, um…"] },
  { id:"bismarck", name:"Otto von Bismarck", short:"Bismarck", cls:"Heavy", spd:4, acc:2, hnd:2, wt:5,
    look:{hair:"pickel", hc:0xb0b0b0, suit:0x1f3a5f, kart:0x2b3a55, acc2:0xd4af37},
    ability:{name:"Unification", type:"pull", desc:"Pulls nearby racers toward him… then rams."},
    lines:["Blood and iron!", "Unity!", "Realpolitik!"] },
  { id:"adenauer", name:"Konrad Adenauer", short:"Adenauer", cls:"Heavy", spd:3, acc:3, hnd:2, wt:5,
    look:{hair:"bald", hc:0xaaaaaa, suit:0x333333, kart:0x0b3d91, acc2:0xffcc00},
    ability:{name:"The Old One", type:"anchor", desc:"Becomes unmovable and rams others away."},
    lines:["No experiments!", "What is that?", "The Old One drives!"] },
  { id:"brandt", name:"Willy Brandt", short:"Brandt", cls:"Technical", spd:3, acc:4, hnd:4, wt:3,
    look:{hair:"short", hc:0x5a4a3a, suit:0x444455, kart:0xe63946, acc2:0xffffff},
    ability:{name:"New Eastern Policy", type:"route", desc:"Opens a safe alternate route ahead."},
    lines:["Dare to have more democracy!", "Growing together!", "Change through rapprochement!"] },
  { id:"merkel", name:"Angela Merkel", short:"Merkel", cls:"Balanced", spd:3, acc:3, hnd:3, wt:3,
    look:{hair:"bob", hc:0xc8a060, suit:0x1e88e5, kart:0x1565c0, acc2:0xffd54f},
    ability:{name:"Caretaker Mode", type:"absorb", desc:"Absorbs one item hit without losing speed."},
    lines:["We can do this.", "There is no alternative.", "Uncharted territory."] },
];

// ===== ITEMS =====
export const ITEMS = {
  pretzel:    { icon:"🥨", name:"Pretzel", desc:"Light homing. Hold S to throw backward." },
  pretzel3:   { icon:"🥨", name:"Triple Pretzel", desc:"Three pretzels orbit as a shield." },
  potato:     { icon:"🥔", name:"Potato", desc:"Bounces chaotically across the track." },
  cone:       { icon:"🚧", name:"Traffic Cone", desc:"Drop an obstacle behind you." },
  barrier:    { icon:"🚧", name:"Road Barrier", desc:"A construction barrier across the road." },
  ice:        { icon:"🚄", name:"Mini Bullet Train", desc:"Races down the track and clears everything in its path." },
  boar:       { icon:"🐗", name:"Wild Boar", desc:"Charges ahead, smashing obstacles and gates." },
  roller:     { icon:"🛞", name:"Steamroller", desc:"Flattens everything, including road barriers." },
  autobahn:   { icon:"💨", name:"Highway Pass", desc:"No speed limit! Big boost." },
  engineering:{ icon:"🛠️", name:"Engineering", desc:"Invulnerable and faster." },
  wrench:     { icon:"🔧", name:"Wrench", desc:"Quick repair: armor + boost." },
  cuckoo:     { icon:"🕰️", name:"Cuckoo Clock", desc:"Reverses the steering of nearby rivals." },
  magnet:     { icon:"🧲", name:"Magnet", desc:"Pulls you toward the racer ahead. Double effect on metal vehicles!" },
  fog:        { icon:"🌫️", name:"Fog Machine", desc:"Thick fog for everyone behind you." },
  stein:      { icon:"🍺", name:"Beer Stein", desc:"Bouncing stein. Turns into a ramp on water." },
  duck:       { icon:"🦆", name:"Rubber Duck", desc:"Floats on water and builds ramps. Squeak!" },
  railswitch: { icon:"🔀", name:"Switch Operator", desc:"Opens every switch shortcut." },
  bomb:       { icon:"💣", name:"Bomb", desc:"Blows up gates, cranes, and rivals." },
  zeppelin:   { icon:"🎈", name:"Zeppelin", desc:"Drops a payload on the leader." },
  gnome:      { icon:"🧙", name:"Garden Gnome", desc:"A mine that explodes on contact." },
  sauerkraut: { icon:"🥬", name:"Cabbage", desc:"A slippery puddle behind you." },
  dackel:     { icon:"🐕", name:"Dachshund", desc:"Chases the nearest rival and bites their tire." },
  grill:      { icon:"🔥", name:"Grill Smoke", desc:"A cloud of smoke that slows pursuers." },
  espresso:   { icon:"☕", name:"Espresso", desc:"A quick jolt of acceleration and drift charge." },
  schirm:     { icon:"☂️", name:"Lucky Umbrella", desc:"Blocks the next hit and gives a small boost." },
  schnitzel:  { icon:"🍽️", name:"Schnitzel", desc:"A bouncing dinner plate that spins out a rival." },
};
// weight tables by place bucket (front -> back)
export const ITEM_TABLE = [
  { pretzel:5, potato:4, cone:4, barrier:3, sauerkraut:3, gnome:3, stein:2, duck:2, pretzel3:2, fog:1, railswitch:1, grill:2, espresso:2, schnitzel:2 },
  { pretzel:3, pretzel3:3, potato:3, stein:3, duck:2, boar:2, cuckoo:2, magnet:2, dackel:2, bomb:2, wrench:2, railswitch:1, autobahn:1, cone:1, gnome:1, schirm:2, espresso:1 },
  { pretzel3:2, boar:3, dackel:3, magnet:3, autobahn:3, cuckoo:2, bomb:2, wrench:2, roller:2, ice:1, zeppelin:1, fog:1, schnitzel:2 },
  { autobahn:4, ice:3, roller:3, engineering:3, zeppelin:3, magnet:2, dackel:2, boar:1, wrench:1, schirm:2, espresso:1 },
];
