// ===== Wunderkart track definitions (see track.js for the DSL) =====
const SKY = { day: [0x4a9cff, 0xdff2ff], dusk: [0x3a2a6a, 0xffa86a], night: [0x0a0f2a, 0x2a3a6a], alp: [0x2f7fe0, 0xe8f4ff], grey: [0x7a8a9a, 0xd0d8e0], sea: [0x3a8ae0, 0xd8f0ff], candy: [0xff8ad8, 0xffe8f8] };
export const TRACKS = [
  // ---------------- 1 Berlin Circuit ----------------
  { id: "berlin", name: "Berlin Circuit", hw: 11, start: { h: 0 },
    theme: { sky: SKY.day, ground: 0x6a9a5a, groundTex: "city" },
    segs: [
      { k: "S", len: 150, env: "city", f: [{ t: "box", at: 0.55, n: 5 }, { t: "sign", at: 0.1, text: "BERLIN 0 KM" }] },
      { k: "T", ang: 90, r: 55, env: "city", core: { k: "tower", w: 26, c: 0xc8c0b0 } },
      { k: "S", len: 70, env: "street", dy: -12, ease: 1, f: [{ t: "obst", at: 0.5, kind: "cone", n: 6, spread: 14 }] },
      { k: "S", len: 120, env: "subway", f: [{ t: "boost", at: 0.4 }, { t: "box", at: 0.75, n: 4 }] },
      { k: "T", ang: -70, r: 70, env: "subway", dy: 4 },
      { k: "S", len: 70, env: "street", dy: 14, ease: 1, f: [{ t: "ramp", at: 0.92, h: 2.4, p: 20 }] },
      { k: "T", ang: 110, r: 50, env: "city", dy: 6, core: { k: "apartment", w: 30, c: 0xe8d8b8 } },
      { k: "S", len: 110, env: "bridge", dy: 8, f: [{ t: "box", at: 0.3 }] },
      { k: "T", ang: 80, r: 65, env: "city", dy: -10 },
      { k: "S", len: 190, env: "city", dy: -6, f: [{ t: "obst", at: 0.5, kind: "barrier", n: 3, spread: 16 }, { t: "boost", at: 0.85, lat: 4 }] },
      { k: "T", ang: 60, r: 75, env: "city", f: [{ t: "box", at: 0.5, n: 5 }] },
      { k: "S", len: 220, env: "city", f: [{ t: "sign", at: 0.1, text: "UNDER THE LINDEN TREES" }, { t: "boost", at: 0.5, lat: -4 }, { t: "box", at: 0.75, n: 5 }] },
      { k: "T", ang: 90, r: 60, env: "city" },
      { k: "S", len: 60, env: "city" },
    ],
    events: [
      { t: "train", seg: 3, at: 0.6, period: 9, off: 0 },
      { t: "traffic", seg: 9, at: 0.1, len: 80, n: 3, speed: 14, dir: -1 },
      { t: "drawbridge", seg: 7, at: 0.45, len: 20, period: 10, p: 22 },
    ],
    lms: [{ kind: "brandenburg", seg: 0, at: 0.35, side: -1, off: 30 }, { kind: "tvtower", seg: 10, at: 0.5, side: 1, off: 120 }, { kind: "skyline", seg: 8, at: 0.5, side: 1, off: 160 }],
  },
  // ---------------- 2 Oktoberfest Fun ----------------
  { id: "wiesn", name: "Oktoberfest Fun", hw: 11, start: { h: 90 },
    theme: { sky: SKY.dusk, ground: 0x7aa04a, fogFar: 1400 },
    segs: [
      { k: "S", len: 120, env: "fair", f: [{ t: "box", at: 0.6, n: 5 }, { t: "banner", at: 0.05, text: "IT'S TAPPED!" }] },
      { k: "T", ang: 100, r: 45, env: "fair", core: { k: "tree", w: 10, c: 0x2a6a35 } },
      { k: "S", len: 140, env: "tent", f: [{ t: "obst", at: 0.35, kind: "table", n: 6, spread: 16 }, { t: "obst", at: 0.7, kind: "barrel", n: 4, spread: 12 }, { t: "cheer", at: 0.5 }] },
      { k: "T", ang: -90, r: 40, env: "tent", f: [{ t: "box", at: 0.5 }] },
      { k: "S", len: 50, env: "fair", dy: 6 },
      { k: "S", len: 80, env: "coaster", dy: 30, ease: 1 },
      { k: "LOOP", r: 15, env: "coaster" },
      { k: "T", ang: 150, r: 40, env: "coaster", dy: -18, roll: 0.35 },
      { k: "S", len: 90, env: "coaster", dy: -18, f: [{ t: "boost", at: 0.6 }] },
      { k: "T", ang: 50, r: 50, env: "fair", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 260, env: "fair", f: [{ t: "obst", at: 0.3, kind: "barrel", n: 4, spread: 16 }, { t: "boost", at: 0.6, lat: 4 }, { t: "ramp", at: 0.9, h: 2, p: 18 }] },
      { k: "T", ang: 70, r: 50, env: "fair" },
      { k: "S", len: 80, env: "fair", f: [{ t: "obst", at: 0.5, kind: "hay", n: 4, spread: 14 }] },
      { k: "T", ang: 80, r: 60, env: "fair" },
    ],
    events: [
      { t: "barrels", seg: 2, at: 0.2, len: 90, n: 4, speed: 10 },
      { t: "swing", seg: 10, at: 0.5, r: 9, kind: "hammer", speed: 1.4 },
      { t: "rotor", seg: 4, at: 0.5, r: 8, speed: 1.2 },
    ],
    lms: [{ kind: "riesenrad", seg: 9, at: 0.5, side: -1, off: 50 }, { kind: "tent", seg: 0, at: 0.5, side: 1, off: 40 }, { kind: "beer", seg: 11, at: 0.4, side: 1, off: 30 }],
  },
  // ---------------- 3 Black Forest Cuckoo ----------------
  { id: "schwarzwald", name: "Black Forest", hw: 10, start: { h: 0 },
    theme: { sky: SKY.day, ground: 0x2f5a2a, groundTex: "forest", fogNear: 160, fogFar: 900, mtns: [14, 0x2a4a2a, false] },
    segs: [
      { k: "S", len: 100, env: "village", f: [{ t: "box", at: 0.6, n: 4 }] },
      { k: "T", ang: -80, r: 50, env: "forest", dy: 10, core: { k: "tree", w: 14, c: 0x1f4a22 } },
      { k: "S", len: 90, env: "forest", dy: 18, ease: 1, f: [{ t: "obst", at: 0.5, kind: "tree", n: 3, spread: 12 }] },
      { k: "T", ang: 140, r: 40, env: "forest", dy: 8 },
      { k: "S", len: 70, env: "rocktunnel", dy: 4, f: [{ t: "box", at: 0.5 }] },
      { k: "T", ang: 90, r: 45, env: "mudtrail", dy: -6, f: [{ t: "patch", at: 0.4, len: 30, surf: "water", w: 6 }] },
      { k: "S", len: 180, env: "forest", dy: -18, f: [{ t: "ramp", at: 0.85, h: 3, p: 24, boost: 1 }] },
      { k: "S", len: 100, env: "river", dy: -4, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 130, r: 55, env: "forest", dy: -10, f: [{ t: "box", at: 0.5, n: 5 }] },
      { k: "S", len: 90, env: "village", dy: -2, f: [{ t: "boost", at: 0.5 }] },
      { k: "T", ang: 80, r: 60, env: "village" },
    ],
    events: [
      { t: "boulder", seg: 2, at: 0.1, len: 80, n: 2, speed: 18 },
      { t: "debris", seg: 8, at: 0.3, len: 50, n: 6, lap: 2, c: 0x5a3a1a },
      { t: "swing", seg: 4, at: 0.6, r: 8, kind: "axe", speed: 1.6 },
    ],
    lms: [{ kind: "cuckoo", seg: 9, at: 0.5, side: -1, off: 26, s: 1.4 }, { kind: "chalet", seg: 0, at: 0.4, side: 1, off: 24 }, { kind: "forest", seg: 6, at: 0.5, side: 1, off: 50 }],
  },
  // ---------------- 4 Hamburg Harbor ----------------
  { id: "hafen", name: "Hamburg Harbor", hw: 11, start: { h: -90 },
    theme: { sky: SKY.grey, ground: 0x3a6a8a, groundTex: "water", fogFar: 1300 },
    segs: [
      { k: "S", len: 220, env: "harbor", f: [{ t: "box", at: 0.5, n: 5 }, { t: "obst", at: 0.8, kind: "crate", n: 4, spread: 14 }] },
      { k: "T", ang: 90, r: 50, env: "harbor" },
      { k: "S", len: 160, env: "pier", dy: 2, f: [{ t: "gap", at: 0.5, len: 14, ramp: 1, p: 22 }] },
      { k: "T", ang: 120, r: 40, env: "ship", dy: 10 },
      { k: "S", len: 110, env: "ship", dy: 2, f: [{ t: "obst", at: 0.4, kind: "barrel", n: 5, spread: 14 }, { t: "box", at: 0.7 }] },
      { k: "T", ang: -60, r: 60, env: "harbor", dy: -12, f: [{ t: "ramp", at: 0.1, h: 2.5, p: 20 }] },
      { k: "S", len: 90, env: "warehouse", f: [{ t: "obst", at: 0.5, kind: "crate", n: 6, spread: 18 }] },
      { k: "T", ang: 110, r: 45, env: "harbor", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 110, env: "bridge", dy: 14, ease: 1 },
      { k: "S", len: 90, env: "bridge", dy: -14, ease: 1, f: [{ t: "boost", at: 0.3 }] },
      { k: "T", ang: 100, r: 55, env: "harbor" },
    ],
    events: [
      { t: "crane", seg: 0, at: 0.6, side: 1, off: 18 },
      { t: "crane", seg: 6, at: 0.3, side: -1, off: 16 },
      { t: "drawbridge", seg: 9, at: 0.05, len: 18, period: 12, p: 22 },
      { t: "traffic", seg: 7, at: 0, len: 60, n: 2, speed: 10, type: "trolley" },
    ],
    lms: [{ kind: "elphi", seg: 1, at: 0.5, side: -1, off: 80, s: 1.2 }, { kind: "harbor", seg: 4, at: 0.5, side: 1, off: 60 }],
  },
  // ---------------- 5 Highway A7 ----------------
  { id: "autobahn", name: "Highway A7", hw: 14, start: { h: 0 },
    theme: { sky: SKY.day, ground: 0x6aa04a, groundTex: "field", fogFar: 2000, mtns: [10, 0x5a7a5a, false] },
    segs: [
      { k: "S", len: 320, env: "autobahn", f: [{ t: "sign", at: 0.05, text: "WUNDERKART EXIT" , bg: "#1a4aa8" }, { t: "box", at: 0.4, n: 6 }, { t: "boost", at: 0.7, lat: -6 }, { t: "boost", at: 0.7, lat: 6 }] },
      { k: "T", ang: 60, r: 140, env: "autobahn", dy: 12 },
      { k: "S", len: 200, env: "bridge", dy: 16, hw: 13, f: [{ t: "box", at: 0.5, n: 6 }] },
      { k: "T", ang: 70, r: 120, env: "highway", dy: -10 },
      { k: "S", len: 160, env: "tunnel", hw: 12, dy: -14, f: [{ t: "boost", at: 0.5 }] },
      { k: "T", ang: 50, r: 110, env: "highway", dy: -4, f: [{ t: "obst", at: 0.5, kind: "barrier", n: 4, spread: 20 }] },
      { k: "S", len: 260, env: "autobahn", f: [{ t: "sign", at: 0.1, text: "TRAFFIC JAM 3 KM", bg: "#cc1111" }, { t: "obst", at: 0.5, kind: "car", n: 3, spread: 18 }, { t: "box", at: 0.8, n: 6 }] },
      { k: "T", ang: 90, r: 130, env: "autobahn" },
      { k: "S", len: 160, env: "construction", hw: 11, f: [{ t: "obst", at: 0.3, kind: "cone", n: 8, spread: 18 }, { t: "ramp", at: 0.7, h: 3, p: 24, boost: 1 }] },
      { k: "T", ang: 90, r: 120, env: "autobahn" },
      { k: "S", len: 120, env: "autobahn" },
    ],
    events: [
      { t: "traffic", seg: 0, at: 0, len: 300, n: 5, speed: 22, dir: 1 },
      { t: "traffic", seg: 6, at: 0, len: 250, n: 4, speed: 18, dir: -1, flip: 1 },
      { t: "traffic", seg: 2, at: 0, len: 190, n: 3, speed: 20, dir: 1, type: "car" },
      { t: "debris", seg: 8, at: 0.4, len: 60, n: 6, lap: 2, c: 0xff6a00 },
    ],
    lms: [{ kind: "highway", seg: 0, at: 0.5, side: 1, off: 60 }, { kind: "town", seg: 7, at: 0.5, side: 1, off: 140 }, { kind: "bus", seg: 10, at: 0.5, side: -1, off: 24 }],
  },
  // ---------------- 6 Zugspitze ----------------
  { id: "zugspitze", name: "Zugspitze", hw: 10, start: { h: 0 },
    theme: { sky: SKY.alp, ground: 0xe8eef4, groundTex: "snow", fogFar: 1600, mtns: [16, 0x8a9aaa, true] },
    segs: [
      { k: "S", len: 120, env: "village", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 120, r: 40, env: "mountain", dy: 14 },
      { k: "S", len: 120, env: "mountain", dy: 24, f: [{ t: "obst", at: 0.5, kind: "rock", n: 2, spread: 10 }] },
      { k: "T", ang: -150, r: 32, env: "pass", dy: 14, f: [{ t: "box", at: 0.5 }] },
      { k: "S", len: 90, env: "pass", dy: 18 },
      { k: "LIFT", h: 40, env: "elevator" },
      { k: "S", len: 90, env: "glacier", dy: 4, f: [{ t: "box", at: 0.4, n: 4 }, { t: "obst", at: 0.7, kind: "snowman", n: 4, spread: 14 }] },
      { k: "T", ang: 110, r: 50, env: "snow", dy: -6, core: { k: "rock", w: 30, c: 0x8a8a90 } },
      { k: "S", len: 140, fixed: 1, env: "snow", dy: -40, ease: 1, f: [{ t: "ramp", at: 0.4, h: 3, p: 24 }, { t: "boost", at: 0.8 }] },
      { k: "T", ang: 140, r: 45, env: "pass", dy: -20 },
      { k: "S", len: 120, env: "rocktunnel", dy: -24, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: -30, r: 70, env: "mountain", dy: -14 },
      { k: "S", len: 90, env: "mountain", dy: -10 },
      { k: "T", ang: 170, r: 55, env: "village", dy: 0 },
    ],
    events: [
      { t: "avalanche", seg: 8, at: 0.2, len: 90, lap: 2, n: 8, dir: 1 },
      { t: "boulder", seg: 2, at: 0.1, len: 100, n: 2, speed: 16 },
      { t: "collapse", seg: 6, at: 0.6, len: 18, lap: 3, sign: "GLACIER COLLAPSE!" },
    ],
    lms: [{ kind: "summitcross", seg: 6, at: 0.5, side: -1, off: 30, y: 6 }, { kind: "chalet", seg: 0, at: 0.4, side: 1, off: 26 }, { kind: "alps", seg: 9, at: 0.5, side: 1, off: 220 }],
  },
  // ---------------- 7 Cologne Cathedral ----------------
  { id: "koeln", name: "Cologne Cathedral", hw: 11, start: { h: 180 },
    theme: { sky: SKY.grey, ground: 0x7a8a6a, groundTex: "city" },
    segs: [
      { k: "S", len: 260, env: "city", f: [{ t: "box", at: 0.5, n: 5 }] },
      { k: "T", ang: -90, r: 45, env: "city" },
      { k: "S", len: 160, env: "cathedral", hw: 13, f: [{ t: "obst", at: 0.3, kind: "pillar", lats: [-9, 9], n: 2 }, { t: "obst", at: 0.6, kind: "pillar", lats: [-9, 9], n: 2 }, { t: "box", at: 0.45, n: 5 }, { t: "slowmo", at: 0.8 }] },
      { k: "T", ang: -90, r: 40, env: "stairs", dy: 14 },
      { k: "S", len: 80, fixed: 1, env: "stairs", dy: 20 },
      { k: "T", ang: -90, r: 36, env: "tower", dy: 16, core: { k: "tower", w: 22, c: 0x5a5448 } },
      { k: "S", len: 110, fixed: 1, env: "roof", dy: 2, f: [{ t: "box", at: 0.4 }, { t: "ramp", at: 0.92, h: 3, p: 26, boost: 1 }] },
      { k: "S", len: 110, fixed: 1, env: "city", dy: -46, ease: 1 },
      { k: "T", ang: 120, r: 60, env: "city", dy: -6, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 160, env: "bridge", f: [{ t: "boost", at: 0.5, lat: 3 }] },
      { k: "T", ang: -150, r: 55, env: "city" },
      { k: "S", len: 110, env: "village", f: [{ t: "obst", at: 0.5, kind: "barrel", n: 5, spread: 14 }] },
      { k: "T", ang: -60, r: 60, env: "city" },
    ],
    events: [
      { t: "swing", seg: 2, at: 0.5, r: 10, kind: "ball", speed: 1.1 },
      { t: "debris", seg: 6, at: 0.3, len: 60, n: 5, lap: 2, c: 0x6a6458 },
      { t: "traffic", seg: 11, at: 0, len: 100, n: 2, speed: 9, type: "trolley" },
    ],
    lms: [{ kind: "dom", seg: 2, at: 0.5, side: -1, off: 10, s: 1.3 }, { kind: "rathaus", seg: 0, at: 0.5, side: 1, off: 26 }, { kind: "river", seg: 9, at: 0.5, side: 1, off: 50 }],
  },
  // ---------------- 8 Rhine Vineyard ----------------
  { id: "rhein", name: "Rhine Vineyard", hw: 10, start: { h: 90 },
    theme: { sky: SKY.day, ground: 0x5a8a3a, groundTex: "field", mtns: [10, 0x4a6a3a, false] },
    segs: [
      { k: "S", len: 100, env: "river", sh: "gravel", surf: "asphalt", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: -90, r: 45, env: "vineyard", dy: 10 },
      { k: "S", len: 90, env: "vineyard", dy: 16, f: [{ t: "obst", at: 0.5, kind: "barrel", n: 3, spread: 10 }] },
      { k: "T", ang: 180, r: 32, env: "vineyard", dy: 10, wall: "fence" },
      { k: "S", len: 90, env: "vineyard", dy: 14, f: [{ t: "box", at: 0.5 }] },
      { k: "T", ang: -180, r: 34, env: "vineyard", dy: 10, wall: "fence" },
      { k: "S", len: 100, env: "castleyard", dy: 6, f: [{ t: "box", at: 0.4, n: 4 }, { t: "obst", at: 0.7, kind: "hay", n: 3 }] },
      { k: "T", ang: 150, r: 40, env: "rampart", dy: 4, core: { k: "castle", w: 34, c: 0xb8a888 } },
      { k: "S", len: 150, fixed: 1, env: "forest", dy: -40, ease: 1, f: [{ t: "ramp", at: 0.5, h: 3, p: 24 }] },
      { k: "T", ang: 120, r: 60, env: "street", dy: -20, f: [{ t: "boost", at: 0.5 }] },
      { k: "S", len: 300, env: "beach", dy: -6, f: [{ t: "box", at: 0.3, n: 4 }, { t: "patch", at: 0.55, len: 70, w: 8, lat: 3, surf: "water" }, { t: "boost", at: 0.85 }] },
      { k: "T", ang: 180, r: 70, env: "river", surf: "asphalt", dy: 0 },
    ],
    events: [
      { t: "barrels", seg: 8, at: 0.1, len: 110, n: 5, speed: 14 },
      { t: "flood", seg: 10, at: 0.1, len: 80, lap: 2 },
      { t: "geyser", seg: 0, at: 0.6, lat: 4, period: 4, p: 20 },
    ],
    lms: [{ kind: "castle", seg: 6, at: 0.5, side: 1, off: 40 }, { kind: "river", seg: 0, at: 0.5, side: -1, off: 40 }, { kind: "town", seg: 11, at: 0.5, side: -1, off: 90 }],
  },
  // ---------------- 9 Zollverein Coal Mine ----------------
  { id: "zeche", name: "Ruhr Coal Mine", hw: 10, start: { h: 0 },
    theme: { sky: SKY.dusk, ground: 0x4a4a40, groundTex: "dirt", fogFar: 1200 },
    segs: [
      { k: "S", len: 150, env: "industrial", f: [{ t: "box", at: 0.5, n: 4 }, { t: "sign", at: 0.1, text: "GOOD LUCK!", bg: "#222" }] },
      { k: "T", ang: 90, r: 45, env: "industrial", core: { k: "silo", w: 18, c: 0x8a6a4a } },
      { k: "S", len: 80, env: "mine", fixed: 1, dy: -20, ease: 1 },
      { k: "T", ang: -120, r: 40, env: "mine", dy: -6, f: [{ t: "box", at: 0.5 }] },
      { k: "S", len: 140, env: "mine", f: [{ t: "obst", at: 0.3, kind: "tnt", n: 3, spread: 10 }, { t: "boost", at: 0.6 }, { t: "obst", at: 0.8, kind: "barrel", n: 3 }] },
      { k: "T", ang: 150, r: 35, env: "cave", dy: 4 },
      { k: "LIFT", h: 34, env: "elevator", speed: 14 },
      { k: "S", len: 220, env: "scaffold", dy: 4, f: [{ t: "box", at: 0.4, n: 3 }, { t: "gap", at: 0.75, len: 12, ramp: 1, p: 22 }] },
      { k: "T", ang: 120, r: 45, env: "industrial", dy: -6 },
      { k: "S", len: 280, env: "industrial", dy: -10, f: [{ t: "obst", at: 0.5, kind: "barrier", n: 3, spread: 14 }, { t: "box", at: 0.8, n: 4 }] },
      { k: "T", ang: 120, r: 55, env: "street" },
    ],
    events: [
      { t: "crusher", seg: 4, at: 0.45, lat: -3, off: 0 },
      { t: "crusher", seg: 4, at: 0.55, lat: 3, off: 1 },
      { t: "barrels", seg: 9, at: 0.1, len: 120, n: 4, speed: 12 },
      { t: "train", seg: 0, at: 0.7, period: 11, off: 3 },
    ],
    lms: [{ kind: "rail", seg: 0, at: 0.5, side: 1, off: 40 }, { kind: "city", seg: 10, at: 0.5, side: 1, off: 160 }],
  },
  // ---------------- 10 Airport ----------------
  { id: "flughafen", name: "Frankfurt Airport", hw: 12, start: { h: 90 },
    theme: { sky: SKY.day, ground: 0x7aa05a, groundTex: "field", fogFar: 2200 },
    segs: [
      { k: "S", len: 380, env: "runway", f: [{ t: "box", at: 0.3, n: 7 }, { t: "boost", at: 0.5, lat: -8 }, { t: "boost", at: 0.5, lat: 8 }, { t: "ramp", at: 0.85, h: 3.5, p: 30, boost: 1, w: 12 }] },
      { k: "T", ang: 90, r: 70, env: "airport" },
      { k: "S", len: 120, env: "airport", f: [{ t: "obst", at: 0.5, kind: "suitcase", n: 6, spread: 16 }] },
      { k: "T", ang: 90, r: 45, env: "airport", dy: 8 },
      { k: "S", len: 150, env: "terminal", dy: 4, f: [{ t: "obst", at: 0.3, kind: "trolley", n: 4, spread: 14 }, { t: "box", at: 0.55, n: 5 }, { t: "obst", at: 0.8, kind: "pillar", lats: [-7, 7], n: 2 }] },
      { k: "T", ang: -90, r: 35, env: "terminal", f: [{ t: "slowmo", at: 0.5 }] },
      { k: "S", len: 110, env: "baggage", conv: 8, dy: -10, f: [{ t: "obst", at: 0.5, kind: "suitcase", n: 5, spread: 8 }] },
      { k: "T", ang: 180, r: 40, env: "baggage", conv: 8, dy: -6 },
      { k: "S", len: 300, env: "tunnel", dy: 4, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 60, env: "airport" },
    ],
    events: [
      { t: "traffic", seg: 0, at: 0.1, len: 300, n: 3, speed: 16, dir: -1, type: "car" },
      { t: "traffic", seg: 4, at: 0.1, len: 120, n: 3, speed: 6, type: "trolley" },
      { t: "rotor", seg: 2, at: 0.2, r: 7, speed: 1.5 },
    ],
    lms: [{ kind: "station", seg: 4, at: 0.5, side: 1, off: 40 }, { kind: "skyline", seg: 0, at: 0.5, side: -1, off: 300 }],
  },
  // ---------------- 11 Neuschwanstein ----------------
  { id: "schloss", name: "Neuschwanstein", hw: 10, start: { h: 0 },
    theme: { sky: SKY.alp, ground: 0x4a7a3a, groundTex: "forest", mtns: [14, 0x7a8a9a, true] },
    segs: [
      { k: "S", len: 120, env: "village", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: -60, r: 50, env: "forest", dy: 12 },
      { k: "S", len: 110, env: "bridge", dy: 14, hw: 9, f: [{ t: "box", at: 0.5 }] },
      { k: "T", ang: 140, r: 35, env: "castleyard", dy: 10 },
      { k: "S", len: 90, env: "hall", dy: 2, f: [{ t: "obst", at: 0.4, kind: "table", n: 4, spread: 12 }, { t: "slowmo", at: 0.7 }] },
      { k: "T", ang: 70, r: 30, env: "tower", dy: 12, core: { k: "castle", w: 20, c: 0xe8e4dc } },
      { k: "S", len: 100, env: "rampart", fixed: 1, dy: 2, f: [{ t: "box", at: 0.5, n: 3 }, { t: "ramp", at: 0.7, h: 2.5, p: 18 }] },
      { k: "S", len: 160, env: "forest", fixed: 1, dy: -50, ease: 1 },
      { k: "T", ang: 60, r: 50, env: "forest", dy: -6, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 140, env: "street", dy: -2, f: [{ t: "obst", at: 0.5, kind: "cow", n: 2, spread: 10 }] },
      { k: "T", ang: 150, r: 80, env: "village" },
    ],
    events: [
      { t: "drawbridge", seg: 2, at: 0.35, len: 16, period: 9, p: 18 },
      { t: "swing", seg: 4, at: 0.5, r: 8, kind: "axe", speed: 1.5 },
      { t: "traffic", seg: 9, at: 0.1, len: 120, n: 2, speed: 4, kind: "cow" },
    ],
    lms: [{ kind: "neuschwanstein", seg: 7, at: 0.3, side: 1, off: 80, s: 1.2 }, { kind: "rapunzel", seg: 10, at: 0.5, side: -1, off: 50 }, { kind: "alps", seg: 0, at: 0.5, side: 1, off: 250 }],
  },
  // ---------------- 12 KaDeWe ----------------
  { id: "kaufhaus", name: "Department Store", hw: 10, start: { h: 0 },
    theme: { sky: SKY.night, ground: 0x3a3a4a, groundTex: "city", fogFar: 1000 },
    segs: [
      { k: "S", len: 110, env: "city", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 35, env: "lobby" },
      { k: "S", len: 120, env: "mall", f: [{ t: "obst", at: 0.3, kind: "trolley", n: 4, spread: 14 }, { t: "box", at: 0.6, n: 5 }] },
      { k: "S", len: 70, env: "escalator", fixed: 1, conv: 8, dy: 14 },
      { k: "T", ang: 180, r: 26, env: "mall", dy: 2 },
      { k: "S", len: 90, env: "store", f: [{ t: "obst", at: 0.5, kind: "crate", n: 5, spread: 12 }] },
      { k: "T", ang: -90, r: 30, env: "foodcourt", f: [{ t: "obst", at: 0.5, kind: "table", n: 4, spread: 12 }] },
      { k: "S", len: 80, env: "foodcourt", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "LIFT", h: 26, env: "elevator" },
      { k: "S", len: 120, env: "roof", f: [{ t: "box", at: 0.3 }, { t: "boost", at: 0.6 }, { t: "ramp", at: 0.95, h: 3, p: 26 }] },
      { k: "T", ang: 150, r: 40, env: "skybridge" },
      { k: "S", len: 120, env: "garage", fixed: 1, dy: -42, ease: 1, f: [{ t: "boost", at: 0.5 }] },
      { k: "T", ang: 30, r: 45, env: "street" },
      { k: "S", len: 60, env: "city" },
    ],
    events: [
      { t: "traffic", seg: 2, at: 0.1, len: 100, n: 3, speed: 5, type: "trolley" },
      { t: "rotor", seg: 7, at: 0.5, r: 7, speed: 1.3 },
      { t: "debris", seg: 9, at: 0.3, len: 60, n: 5, lap: 2, c: 0xff4fa0 },
    ],
    lms: [{ kind: "skyline", seg: 9, at: 0.5, side: 1, off: 150 }, { kind: "fountain", seg: 0, at: 0.5, side: -1, off: 18 }],
  },
  // ---------------- 13 Skyline Mainhattan ----------------
  { id: "skyline", name: "Mainhattan", hw: 10, start: { h: 0, y: 60 }, groundY: -2,
    theme: { sky: SKY.night, ground: 0x1a2a3a, groundTex: "city", fogFar: 1600 },
    segs: [
      { k: "S", len: 140, env: "roof", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 40, env: "sky", dy: 10, core: { k: "sky", w: 34, c: 0x3a5a7a } },
      { k: "S", len: 120, env: "skybridge", dy: 4, f: [{ t: "box", at: 0.5, n: 3 }] },
      { k: "LOOP", r: 16, env: "sky" },
      { k: "T", ang: 90, r: 35, env: "sky", dy: 8, roll: 0.3 },
      { k: "S", len: 100, env: "sky", fixed: 1, dy: -40, ease: 1, f: [{ t: "boost", at: 0.3 }, { t: "ramp", at: 0.9, h: 3, p: 26 }] },
      { k: "S", len: 100, env: "roof", f: [{ t: "gap", at: 0.2, len: 16, ramp: 1, p: 24 }, { t: "box", at: 0.6, n: 4 }] },
      { k: "T", ang: 90, r: 40, env: "skyglass", core: { k: "tower", w: 28, c: 0x7a8aa0 } },
      { k: "S", len: 140, env: "sky", dy: 10, cork: 1, fixed: 1 },
      { k: "S", len: 60, env: "roof", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 45, env: "sky", dy: 8 },
      { k: "S", len: 60, env: "roof" },
    ],
    events: [
      { t: "rotor", seg: 0, at: 0.6, r: 8, speed: 1.4 },
      { t: "collapse", seg: 9, at: 0.4, len: 16, lap: 2, sign: "UNSAFE!" },
      { t: "swing", seg: 6, at: 0.8, r: 9, kind: "ball", speed: 1.2 },
    ],
    lms: [{ kind: "skyline", seg: 0, at: 0.5, side: 1, off: 120, y: -60 }, { kind: "skyline", seg: 6, at: 0.5, side: -1, off: 140, y: -60 }, { kind: "tvtower", seg: 2, at: 0.5, side: 1, off: 200, y: -60 }],
  },
  // ---------------- 14 North Sea Mudflats ----------------
  { id: "nordsee", name: "North Sea Mudflats", hw: 11, start: { h: 0 },
    theme: { sky: SKY.sea, ground: 0xd8c890, groundTex: "sand", fogFar: 1800 },
    segs: [
      { k: "S", len: 160, env: "beach", f: [{ t: "box", at: 0.5, n: 5 }] },
      { k: "T", ang: -90, r: 60, env: "beach", core: { k: "lighthouse", w: 10, c: 0xdd2222 } },
      { k: "S", len: 160, env: "shallows", f: [{ t: "box", at: 0.5, n: 4 }, { t: "ramp", at: 0.8, h: 2, p: 20 }] },
      { k: "T", ang: -90, r: 50, env: "pier", dy: 4 },
      { k: "S", len: 140, env: "pier", dy: 2, f: [{ t: "gap", at: 0.5, len: 14, ramp: 1, p: 22 }, { t: "obst", at: 0.8, kind: "barrel", n: 3 }] },
      { k: "T", ang: -120, r: 40, env: "ship", dy: 6 },
      { k: "S", len: 100, env: "ship", f: [{ t: "obst", at: 0.5, kind: "crate", n: 4, spread: 12 }, { t: "box", at: 0.3, n: 3 }] },
      { k: "T", ang: 60, r: 50, env: "pier", dy: -12 },
      { k: "S", len: 160, env: "beach", f: [{ t: "obst", at: 0.4, kind: "hay", n: 4, spread: 18 }, { t: "boost", at: 0.7 }] },
      { k: "T", ang: -120, r: 60, env: "dirt", dy: 6 },
      { k: "S", len: 120, env: "street", dy: -4, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 0.001, r: 99, env: "beach" },
    ],
    events: [
      { t: "flood", seg: 2, at: 0.1, len: 120, lap: 2 },
      { t: "geyser", seg: 8, at: 0.3, lat: -4, period: 3.5, p: 22 },
      { t: "crane", seg: 6, at: 0.5, side: 1, off: 16 },
    ],
    lms: [{ kind: "harbor", seg: 6, at: 0.5, side: -1, off: 60 }, { kind: "town", seg: 10, at: 0.5, side: 1, off: 70 }],
  },
  // ---------------- 15 Farm ----------------
  { id: "bauernhof", name: "Farm", hw: 10, start: { h: 90 },
    theme: { sky: SKY.day, ground: 0x7ab04a, groundTex: "field", mtns: [10, 0x5a8a4a, false] },
    segs: [
      { k: "S", len: 140, env: "street", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 50, env: "farm", core: { k: "silo", w: 14, c: 0xb8b8b0 } },
      { k: "S", len: 150, env: "barn", f: [{ t: "obst", at: 0.3, kind: "hay", n: 5, spread: 12 }, { t: "box", at: 0.6, n: 3 }, { t: "ramp", at: 0.85, h: 2.5, p: 22 }] },
      { k: "T", ang: 60, r: 45, env: "field", dy: 6 },
      { k: "S", len: 160, env: "field", dy: 10, f: [{ t: "obst", at: 0.4, kind: "cow", n: 3, spread: 16 }, { t: "boost", at: 0.7 }] },
      { k: "T", ang: 30, r: 40, env: "mudtrail", dy: 4, f: [{ t: "patch", at: 0.5, len: 20, surf: "mud", w: 7 }] },
      { k: "S", len: 120, env: "dirt", dy: -14, f: [{ t: "ramp", at: 0.6, h: 3, p: 24 }] },
      { k: "T", ang: 90, r: 45, env: "farm", dy: -6, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 240, env: "field", f: [{ t: "obst", at: 0.5, kind: "hay", n: 4, spread: 16 }, { t: "box", at: 0.75, n: 4 }] },
      { k: "T", ang: 90, r: 60, env: "street" },
    ],
    events: [
      { t: "traffic", seg: 4, at: 0.1, len: 140, n: 3, speed: 3, kind: "cow" },
      { t: "traffic", seg: 8, at: 0.1, len: 140, n: 2, speed: 8, type: "car", dir: -1 },
      { t: "rotor", seg: 6, at: 0.3, r: 9, speed: 1.0 },
    ],
    lms: [{ kind: "chalet", seg: 0, at: 0.5, side: -1, off: 30 }, { kind: "forest", seg: 4, at: 0.5, side: 1, off: 70 }, { kind: "town", seg: 8, at: 0.5, side: 1, off: 120 }],
  },
  // ---------------- 16 Reservoir ----------------
  { id: "talsperre", name: "Reservoir", hw: 10, start: { h: 0 },
    theme: { sky: SKY.day, ground: 0x4a7a3a, groundTex: "forest", mtns: [14, 0x5a6a5a, false] },
    segs: [
      { k: "S", len: 120, env: "street", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 50, env: "mountain", dy: 10 },
      { k: "S", len: 220, env: "mountain", dy: 26, f: [{ t: "box", at: 0.6, n: 3 }] },
      { k: "T", ang: 90, r: 40, env: "mountain", dy: 4 },
      { k: "S", len: 200, env: "dam", f: [{ t: "box", at: 0.4, n: 4 }, { t: "boost", at: 0.7 }, { t: "sign", at: 0.1, text: "DAM WALL", bg: "#335" }] },
      { k: "T", ang: 90, r: 40, env: "rocktunnel", dy: -8 },
      { k: "S", len: 100, env: "industrial", fixed: 1, dy: -26, ease: 1, f: [{ t: "obst", at: 0.5, kind: "barrel", n: 3 }] },
      { k: "T", ang: -60, r: 40, env: "river", dy: -2 },
      { k: "S", len: 160, env: "river", f: [{ t: "box", at: 0.5, n: 4 }, { t: "ramp", at: 0.8, h: 2.5, p: 22 }] },
      { k: "T", ang: 150, r: 50, env: "forest", dy: 0 },
      { k: "S", len: 240, env: "forest", dy: -4, f: [{ t: "obst", at: 0.4, kind: "tree", n: 3, spread: 14 }, { t: "box", at: 0.75, n: 4 }] },
    ],
    events: [
      { t: "flood", seg: 8, at: 0.1, len: 140, lap: 2 },
      { t: "geyser", seg: 4, at: 0.3, lat: 3, period: 3, p: 22 },
      { t: "boulder", seg: 2, at: 0, len: 200, n: 2, speed: 15 },
    ],
    lms: [{ kind: "dam", seg: 4, at: 0.5, side: 1, off: 10 }, { kind: "mountain", seg: 8, at: 0.5, side: -1, off: 160 }],
  },
  // ---------------- 17 BER Airport Construction ----------------
  { id: "baustelle", name: "BER Airport Construction", hw: 11, start: { h: 0 },
    theme: { sky: SKY.grey, ground: 0x8a7a5a, groundTex: "dirt", fogFar: 1400 },
    segs: [
      { k: "S", len: 260, env: "construction", f: [{ t: "box", at: 0.5, n: 4 }, { t: "sign", at: 0.1, text: "OPENING 2011", bg: "#cc1111" }] },
      { k: "T", ang: 90, r: 45, env: "construction", f: [{ t: "obst", at: 0.5, kind: "cone", n: 6, spread: 14 }] },
      { k: "S", len: 90, fixed: 1, env: "scaffold", dy: 16, f: [{ t: "box", at: 0.5 }] },
      { k: "T", ang: 90, r: 30, env: "scaffold", dy: 10 },
      { k: "S", len: 110, fixed: 1, env: "scaffold", dy: 4, f: [{ t: "gap", at: 0.5, len: 14, ramp: 1, p: 22, lap: 2 }] },
      { k: "T", ang: -90, r: 35, env: "terminal", dy: -4 },
      { k: "S", len: 120, env: "terminal", fixed: 1, dy: -20, f: [{ t: "obst", at: 0.5, kind: "trolley", n: 4, spread: 12 }] },
      { k: "T", ang: 90, r: 45, env: "construction", dy: -6, f: [{ t: "patch", at: 0.5, len: 25, surf: "mud", w: 6 }] },
      { k: "S", len: 160, fixed: 1, env: "runway", hw: 14, f: [{ t: "box", at: 0.4, n: 5 }, { t: "ramp", at: 0.75, h: 3, p: 26, boost: 1, w: 10 }] },
      { k: "T", ang: 90, r: 55, env: "construction" },
      { k: "S", len: 250, env: "construction", f: [{ t: "obst", at: 0.5, kind: "barrier", n: 4, spread: 18 }, { t: "box", at: 0.8, n: 4 }] },
      { k: "T", ang: 90, r: 50, env: "street" },
    ],
    events: [
      { t: "crane", seg: 0, at: 0.6, side: 1, off: 16 },
      { t: "crane", seg: 10, at: 0.5, side: -1, off: 16 },
      { t: "collapse", seg: 2, at: 0.6, len: 16, lap: 3, sign: "FIRE SAFETY!" },
      { t: "crusher", seg: 6, at: 0.6, lat: 0, off: 0 },
      { t: "debris", seg: 8, at: 0.2, len: 80, n: 6, lap: 2, c: 0xffaa00 },
    ],
    lms: [{ kind: "station", seg: 8, at: 0.5, side: -1, off: 60 }, { kind: "city", seg: 0, at: 0.5, side: -1, off: 180 }],
  },
  // ---------------- 18 Central Station ----------------
  { id: "bahnhof", name: "Central Station", hw: 11, start: { h: 90 },
    theme: { sky: SKY.dusk, ground: 0x5a6a5a, groundTex: "city" },
    segs: [
      { k: "S", len: 140, env: "city", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: -90, r: 45, env: "city" },
      { k: "S", len: 200, env: "station", hw: 12, f: [{ t: "obst", at: 0.3, kind: "suitcase", n: 5, spread: 14 }, { t: "box", at: 0.5, n: 5 }, { t: "obst", at: 0.7, kind: "pillar", lats: [-8, 8], n: 2 }] },
      { k: "T", ang: -90, r: 40, env: "subway", dy: -8 },
      { k: "S", len: 140, env: "subway", dy: -6, f: [{ t: "boost", at: 0.5 }] },
      { k: "T", ang: -90, r: 40, env: "subway", dy: 6 },
      { k: "S", len: 70, env: "escalator", fixed: 1, conv: 8, dy: 16 },
      { k: "S", len: 120, fixed: 1, env: "train", dy: 4, f: [{ t: "box", at: 0.3, n: 3 }, { t: "gap", at: 0.6, len: 10, ramp: 1, p: 20 }] },
      { k: "T", ang: 120, r: 45, env: "bridge", dy: 4 },
      { k: "S", len: 140, env: "bridge", dy: -10, f: [{ t: "ramp", at: 0.8, h: 2.5, p: 22 }] },
      { k: "T", ang: -150, r: 50, env: "street", dy: -6 },
      { k: "S", len: 100, env: "street", f: [{ t: "obst", at: 0.5, kind: "cone", n: 5, spread: 12 }] },
      { k: "T", ang: -60, r: 60, env: "city" },
    ],
    events: [
      { t: "train", seg: 2, at: 0.4, period: 8, off: 0 },
      { t: "train", seg: 4, at: 0.5, period: 10, off: 4, dir: -1 },
      { t: "traffic", seg: 2, at: 0.1, len: 160, n: 3, speed: 5, type: "trolley" },
    ],
    lms: [{ kind: "station", seg: 2, at: 0.5, side: 1, off: 20, s: 1.3 }, { kind: "rail", seg: 9, at: 0.5, side: 1, off: 40 }],
  },
  // ---------------- 19 Ski Jump ----------------
  { id: "schanze", name: "Ski Jump", hw: 10, start: { h: 0 },
    theme: { sky: SKY.alp, ground: 0xeef2f8, groundTex: "snow", mtns: [16, 0x9aaaba, true] },
    segs: [
      { k: "S", len: 140, env: "snow", f: [{ t: "box", at: 0.5, n: 4 }, { t: "obst", at: 0.8, kind: "snowman", n: 3, spread: 12 }] },
      { k: "T", ang: 90, r: 45, env: "pass", dy: 6 },
      { k: "S", len: 130, env: "pass", dy: 12, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "LIFT", h: 50, env: "elevator", speed: 18 },
      { k: "S", len: 60, env: "skijump", fixed: 1, dy: 2, f: [{ t: "box", at: 0.5, n: 3 }] },
      { k: "T", ang: 90, r: 30, env: "skijump" },
      { k: "S", len: 140, env: "skijump", fixed: 1, dy: -38, f: [{ t: "boost", at: 0.5 }, { t: "ramp", at: 0.97, h: 4, p: 34, boost: 1, w: 10 }] },
      { k: "S", len: 120, env: "snow", fixed: 1, dy: -30, ease: 1, f: [{ t: "slowmo", at: 0.05 }, { t: "cheer", at: 0.4 }] },
      { k: "T", ang: 90, r: 55, env: "glacier", dy: -6, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 150, env: "snow", dy: -4, f: [{ t: "obst", at: 0.5, kind: "tree", n: 4, spread: 16 }] },
      { k: "T", ang: 90, r: 50, env: "forest", sh: "snow", dy: -2 },
      { k: "S", len: 160, env: "village", f: [{ t: "box", at: 0.5, n: 4 }] },
    ],
    events: [
      { t: "avalanche", seg: 8, at: 0.2, len: 120, lap: 2, n: 9, dir: -1 },
      { t: "boulder", seg: 0, at: 0.1, len: 120, n: 3, speed: 12 },
    ],
    lms: [{ kind: "summitcross", seg: 4, at: 0.5, side: 1, off: 20, y: 4 }, { kind: "chalet", seg: 10, at: 0.5, side: -1, off: 26 }, { kind: "alps", seg: 8, at: 0.5, side: 1, off: 260 }],
  },
  // ---------------- 20 Sewers ----------------
  { id: "kanal", name: "Sewers", hw: 10, start: { h: 0 },
    theme: { sky: SKY.night, ground: 0x2a2a2a, groundTex: "city", fogNear: 120, fogFar: 700 },
    segs: [
      { k: "S", len: 120, env: "street", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 40, env: "street", dy: -6 },
      { k: "S", len: 90, env: "sewer", fixed: 1, dy: -18, ease: 1 },
      { k: "S", len: 140, env: "sewer", f: [{ t: "patch", at: 0.4, len: 40, surf: "water", w: 6 }, { t: "box", at: 0.7, n: 4 }] },
      { k: "T", ang: 90, r: 35, env: "sewer", f: [{ t: "obst", at: 0.5, kind: "barrel", n: 3 }] },
      { k: "S", len: 160, env: "cave", dy: -6, f: [{ t: "obst", at: 0.5, kind: "rock", n: 2, spread: 8 }, { t: "boost", at: 0.8 }] },
      { k: "T", ang: 90, r: 35, env: "cave", dy: 4, f: [{ t: "box", at: 0.5, n: 3 }] },
      { k: "S", len: 200, env: "sewer", conv: 10, f: [{ t: "ramp", at: 0.7, h: 2.5, p: 22 }] },
      { k: "T", ang: 90, r: 35, env: "subway", dy: 6 },
      { k: "S", len: 100, env: "subway", fixed: 1, dy: 20, ease: 1, f: [{ t: "box", at: 0.5, n: 3 }] },
      { k: "S", len: 80, env: "street" },
    ],
    events: [
      { t: "barrels", seg: 3, at: 0.1, len: 120, n: 4, speed: 12 },
      { t: "flood", seg: 7, at: 0.1, len: 120, lap: 2 },
      { t: "swing", seg: 5, at: 0.5, r: 8, kind: "ball", speed: 1.4 },
      { t: "geyser", seg: 3, at: 0.6, lat: -3, period: 3, p: 20 },
    ],
    lms: [{ kind: "city", seg: 0, at: 0.5, side: 1, off: 80 }, { kind: "fountain", seg: 11, at: 0.5, side: -1, off: 18 }],
  },
  // ---------------- 21 Fairy-Tale Forest ----------------
  { id: "maerchen", name: "Fairy-Tale Forest", hw: 10, start: { h: 0 },
    theme: { sky: SKY.candy, ground: 0x6ac06a, groundTex: "forest", fogFar: 1200 },
    segs: [
      { k: "S", len: 130, env: "fairy", f: [{ t: "box", at: 0.5, n: 4 }, { t: "banner", at: 0.05, text: "ONCE UPON A TIME…" }] },
      { k: "T", ang: -90, r: 45, env: "forest", core: { k: "tree", w: 18, c: 0x1f6a2a } },
      { k: "S", len: 120, env: "forest", dy: 8, f: [{ t: "obst", at: 0.5, kind: "tree", n: 3, spread: 12 }] },
      { k: "T", ang: 120, r: 35, env: "fairy", dy: 10 },
      { k: "S", len: 100, env: "rocktunnel", dy: 4, f: [{ t: "box", at: 0.5, n: 3 }] },
      { k: "T", ang: 120, r: 32, env: "tower", dy: 16, core: { k: "tower", w: 14, c: 0xc8a8d8 } },
      { k: "S", len: 110, env: "rampart", fixed: 1, f: [{ t: "ramp", at: 0.95, h: 3.5, p: 28, boost: 1 }] },
      { k: "S", len: 110, env: "fairy", fixed: 1, dy: -38, ease: 1, f: [{ t: "boost", at: 0.5 }] },
      { k: "T", ang: -60, r: 50, env: "fairy", f: [{ t: "obst", at: 0.5, kind: "barrel", n: 3 }] },
      { k: "S", len: 140, env: "mudtrail", f: [{ t: "patch", at: 0.4, len: 30, surf: "candy", w: 6 }, { t: "box", at: 0.7, n: 4 }] },
      { k: "T", ang: 270, r: 50, env: "fairy", f: [{ t: "bounce", at: 0.5, p: 20 }] },
    ],
    events: [
      { t: "swing", seg: 4, at: 0.5, r: 8, kind: "axe", speed: 1.3 },
      { t: "rotor", seg: 9, at: 0.6, r: 8, speed: 1.1 },
      { t: "boulder", seg: 2, at: 0, len: 110, n: 2, speed: 14 },
    ],
    lms: [{ kind: "gingerbread", seg: 0, at: 0.5, side: 1, off: 26 }, { kind: "rapunzel", seg: 6, at: 0.5, side: -1, off: 30 }, { kind: "fairy", seg: 9, at: 0.5, side: 1, off: 50 }],
  },
  // ---------------- 22 Apartment Blocks ----------------
  { id: "platte", name: "Apartment Blocks", hw: 10, start: { h: 0 },
    theme: { sky: SKY.grey, ground: 0x6a7a5a, groundTex: "city" },
    segs: [
      { k: "S", len: 120, env: "street", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 35, env: "garage" },
      { k: "S", len: 80, fixed: 1, env: "hallway", f: [{ t: "obst", at: 0.5, kind: "crate", n: 3, spread: 6 }] },
      { k: "T", ang: -90, r: 26, env: "stairs", dy: 12 },
      { k: "S", len: 90, env: "apartment", fixed: 1, f: [{ t: "obst", at: 0.4, kind: "table", n: 3, spread: 8 }, { t: "box", at: 0.7, n: 3 }] },
      { k: "LIFT", h: 24, env: "elevator" },
      { k: "S", len: 110, env: "roof", f: [{ t: "box", at: 0.4 }, { t: "gap", at: 0.8, len: 14, ramp: 1, p: 24 }] },
      { k: "T", ang: 90, r: 40, env: "roof", core: { k: "apartment", w: 30, c: 0xb8b0a0 } },
      { k: "S", len: 120, env: "scaffold", fixed: 1, dy: -20, f: [{ t: "boost", at: 0.6 }] },
      { k: "T", ang: 90, r: 40, env: "street", dy: -14 },
      { k: "S", len: 160, env: "street", f: [{ t: "obst", at: 0.5, kind: "car", n: 2, spread: 10 }, { t: "box", at: 0.75, n: 4 }] },
      { k: "T", ang: 90, r: 45, env: "street", dy: -2 },
      { k: "S", len: 80, env: "street" },
      { k: "T", ang: 90, r: 45, env: "street" },
    ],
    events: [
      { t: "traffic", seg: 10, at: 0.1, len: 140, n: 3, speed: 12, dir: -1 },
      { t: "debris", seg: 6, at: 0.2, len: 60, n: 5, lap: 2, c: 0x8a8a7a },
      { t: "collapse", seg: 8, at: 0.5, len: 14, lap: 3, sign: "DEMOLITION!" },
    ],
    lms: [{ kind: "tvtower", seg: 6, at: 0.5, side: -1, off: 180 }, { kind: "bus", seg: 0, at: 0.5, side: 1, off: 20 }],
  },
  // ---------------- 23 Roller Coaster ----------------
  { id: "achterbahn", name: "Roller Coaster", hw: 9, start: { h: 90 },
    theme: { sky: SKY.dusk, ground: 0x6a9a4a, fogFar: 1500 },
    segs: [
      { k: "S", len: 130, env: "fair", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 90, r: 40, env: "fair" },
      { k: "LIFT", h: 40, env: "elevator", speed: 16 },
      { k: "S", len: 50, env: "coaster", fixed: 1, f: [{ t: "box", at: 0.5, n: 3 }] },
      { k: "S", len: 110, env: "coaster", fixed: 1, dy: -36, ease: 1, f: [{ t: "boost", at: 0.8 }] },
      { k: "LOOP", r: 15, env: "coaster" },
      { k: "T", ang: 120, r: 35, env: "coaster", dy: 10, roll: 0.4 },
      { k: "S", len: 140, env: "coaster", fixed: 1, dy: 4, cork: 1 },
      { k: "T", ang: -120, r: 30, env: "coaster", dy: -6, roll: -0.4 },
      { k: "S", len: 100, env: "tent", fixed: 1, dy: -12, f: [{ t: "obst", at: 0.5, kind: "barrel", n: 3 }] },
      { k: "T", ang: 120, r: 40, env: "fair", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 120, env: "fair", f: [{ t: "ramp", at: 0.5, h: 2.5, p: 22 }] },
      { k: "T", ang: 150, r: 50, env: "fair" },
      { k: "S", len: 60, env: "fair" },
    ],
    events: [
      { t: "rotor", seg: 0, at: 0.6, r: 8, speed: 1.3 },
      { t: "swing", seg: 11, at: 0.3, r: 9, kind: "hammer", speed: 1.5 },
      { t: "traffic", seg: 9, at: 0.1, len: 90, n: 2, speed: 6, type: "barrel" },
    ],
    lms: [{ kind: "coaster", seg: 0, at: 0.5, side: -1, off: 40 }, { kind: "riesenrad", seg: 11, at: 0.5, side: 1, off: 50 }, { kind: "tent", seg: 12, at: 0.5, side: -1, off: 40 }],
  },
  // ---------------- 24 Nordschleife ----------------
  { id: "nordschleife", name: "Nordschleife", hw: 11, start: { h: 0 },
    theme: { sky: SKY.day, ground: 0x3a6a2a, groundTex: "forest", fogFar: 1800, mtns: [12, 0x3a5a3a, false] },
    segs: [
      { k: "S", len: 220, env: "highway", f: [{ t: "box", at: 0.5, n: 5 }, { t: "sign", at: 0.1, text: "GREEN HELL", bg: "#1a5a2a" }] },
      { k: "T", ang: -100, r: 60, env: "rally", dy: -8 },
      { k: "S", len: 140, env: "forest", surf: "asphalt", dy: -16, f: [{ t: "obst", at: 0.5, kind: "hay", n: 3, spread: 14 }] },
      { k: "T", ang: 130, r: 45, env: "rally", dy: -10, f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "S", len: 120, env: "forest", surf: "asphalt", dy: 14, f: [{ t: "ramp", at: 0.9, h: 2.5, p: 22 }] },
      { k: "T", ang: 160, r: 30, env: "rally", dy: 10, roll: 0.45, f: [{ t: "boost", at: 0.7 }] },
      { k: "S", len: 180, env: "highway", dy: 18, f: [{ t: "box", at: 0.5, n: 5 }] },
      { k: "T", ang: -90, r: 50, env: "rally", dy: 4 },
      { k: "S", len: 100, env: "rally", dy: -12, f: [{ t: "obst", at: 0.5, kind: "tree", n: 2, spread: 8 }, { t: "ramp", at: 0.85, h: 3, p: 24 }] },
      { k: "T", ang: 80, r: 45, env: "rally", dy: -6 },
      { k: "S", len: 160, env: "highway", dy: 6, f: [{ t: "box", at: 0.5, n: 5 }] },
      { k: "T", ang: 180, r: 70, env: "highway" },
    ],
    events: [
      { t: "traffic", seg: 6, at: 0.1, len: 160, n: 3, speed: 18, type: "car" },
      { t: "debris", seg: 2, at: 0.3, len: 80, n: 6, lap: 2, c: 0xd8b060 },
      { t: "boulder", seg: 8, at: 0, len: 90, n: 2, speed: 14 },
    ],
    lms: [{ kind: "castle", seg: 6, at: 0.5, side: 1, off: 160 }, { kind: "forest", seg: 2, at: 0.5, side: -1, off: 50 }, { kind: "ring", seg: 0, at: 0.5, side: -1, off: 40 }],
  },
  // ---------------- Moonlit Mill ----------------
  { id: "moonlitmill", name: "Moonlit Mill", laps: 5, hw: 11, start: { h: 0 },
    theme: { sky: SKY.dusk, ground: 0x263b2c, groundTex: "forest", fogFar: 1050, mtns: [10, 0x283c35, false] },
    segs: [
      { k: "S", len: 175, env: "fairy", f: [{ t: "box", at: 0.48, n: 4 }] },
      { k: "T", ang: 120, r: 42, env: "forest", roll: 0.22 },
      { k: "S", len: 100, env: "fairy", f: [{ t: "boost", at: 0.7 }] },
      { k: "T", ang: 60, r: 34, env: "village" },
      { k: "S", len: 125, env: "rocktunnel", f: [{ t: "box", at: 0.55, n: 3 }] },
      { k: "T", ang: -35, r: 55, env: "forest" },
      { k: "S", len: 115, env: "fairy", f: [{ t: "ramp", at: 0.76, h: 2.8, p: 25 }] },
      { k: "T", ang: 130, r: 34, env: "fair", roll: -0.28 },
      { k: "S", len: 95, env: "forest", f: [{ t: "boost", at: 0.32 }] },
      { k: "T", ang: 70, r: 50, env: "village" },
      { k: "S", len: 115, env: "fairy" },
      { k: "T", ang: -25, r: 42, env: "forest" },
      { k: "S", len: 105, env: "fairy", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 60, r: 48, env: "village" },
      { k: "S", len: 120, env: "fairy" },
      { k: "T", ang: -20, r: 55, env: "forest" },
      { k: "S", len: 95, env: "fairy" },
    ],
    events: [{ t: "rotor", seg: 3, at: 0.5, r: 7, speed: 1.4 }, { t: "swing", seg: 7, at: 0.55, r: 8, kind: "lantern", speed: 1.2 }],
    lms: [{ kind: "forest", seg: 0, at: 0.45, side: -1, off: 34 }, { kind: "windmill", seg: 9, at: 0.5, side: 1, off: 30 }],
  },
  // ---------------- Stormglass Harbor ----------------
  { id: "stormglass", name: "Stormglass Harbor", laps: 5, hw: 12, start: { h: 0 },
    theme: { sky: SKY.grey, ground: 0x28617a, groundTex: "water", fogFar: 1200 },
    segs: [
      { k: "S", len: 220, env: "harbor", f: [{ t: "box", at: 0.32, n: 4 }, { t: "obst", at: 0.78, kind: "crate", n: 3, spread: 12 }] },
      { k: "T", ang: 150, r: 44, env: "ship", roll: 0.18 },
      { k: "S", len: 135, env: "pier", f: [{ t: "gap", at: 0.55, len: 18, ramp: 1, p: 26 }] },
      { k: "T", ang: -60, r: 35, env: "harbor" },
      { k: "S", len: 190, env: "ship", f: [{ t: "boost", at: 0.46 }] },
      { k: "T", ang: 140, r: 42, env: "bridge", roll: -0.22 },
      { k: "S", len: 180, env: "pier", f: [{ t: "box", at: 0.65, n: 4 }] },
      { k: "T", ang: 60, r: 54, env: "harbor" },
      { k: "S", len: 140, env: "harbor", f: [{ t: "boost", at: 0.72 }] },
      { k: "T", ang: 110, r: 38, env: "ship" },
      { k: "S", len: 150, env: "pier", f: [{ t: "box", at: 0.45, n: 4 }] },
      { k: "T", ang: -40, r: 60, env: "harbor" },
      { k: "S", len: 135, env: "harbor" },
    ],
    events: [{ t: "drawbridge", seg: 2, at: 0.35, len: 18, period: 10, p: 24 }, { t: "crane", seg: 4, at: 0.48, side: -1, off: 14 }, { t: "barrels", seg: 6, at: 0.15, len: 70, n: 3, speed: 13 }],
    lms: [{ kind: "lighthouse", seg: 7, at: 0.5, side: 1, off: 42 }, { kind: "elphi", seg: 0, at: 0.45, side: -1, off: 35 }],
  },
  // ---------------- Dragonspire Run ----------------
  { id: "dragonspire", name: "Dragonspire Run", laps: 5, hw: 11, start: { h: 0 },
    theme: { sky: SKY.candy, ground: 0x4c4265, groundTex: "rock", fogFar: 1100, mtns: [14, 0x55426e, false] },
    segs: [
      { k: "S", len: 210, env: "castleyard", f: [{ t: "box", at: 0.6, n: 4 }] },
      { k: "T", ang: 180, r: 42, env: "rampart", roll: 0.28 },
      { k: "S", len: 165, env: "tunnel", f: [{ t: "boost", at: 0.6 }] },
      { k: "T", ang: -60, r: 30, env: "castleyard" },
      { k: "S", len: 145, env: "cathedral", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 150, r: 35, env: "rampart", roll: -0.24 },
      { k: "S", len: 130, env: "fairy", cork: 0.5, fixed: 1 },
      { k: "T", ang: -30, r: 55, env: "castleyard", roll: -0.36 },
      { k: "LIFT", h: 90, env: "elevator", speed: 24 },
      { k: "S", len: 185, env: "rampart", dy: -90, ease: 1, f: [{ t: "ramp", at: 0.7, h: 3.2, p: 28, boost: 1 }] },
      { k: "T", ang: 120, r: 40, env: "castleyard" },
      { k: "S", len: 165, env: "fairy", f: [{ t: "boost", at: 0.35 }, { t: "box", at: 0.76, n: 4 }] },
    ],
    events: [{ t: "swing", seg: 4, at: 0.52, r: 9, kind: "ball", speed: 1.45 }, { t: "rotor", seg: 9, at: 0.5, r: 7, speed: 1.35 }],
    lms: [{ kind: "castle", seg: 1, at: 0.5, side: 1, off: 48 }, { kind: "tower", seg: 10, at: 0.5, side: -1, off: 34 }],
  },
  // ---------------- Slipstream Express ----------------
  { id: "slipstream", name: "Slipstream Express", laps: 5, hw: 13, start: { h: 0 },
    theme: { sky: SKY.night, ground: 0x34434c, groundTex: "city", fogFar: 1700 },
    segs: [
      { k: "S", len: 300, env: "runway", f: [{ t: "boost", at: 0.18 }, { t: "box", at: 0.6, n: 5 }, { t: "sign", at: 0.05, text: "NO SPEED LIMIT" }] },
      { k: "T", ang: 110, r: 105, env: "autobahn", roll: 0.12 },
      { k: "S", len: 230, env: "highway", f: [{ t: "box", at: 0.72, n: 4 }] },
      { k: "T", ang: 130, r: 92, env: "bridge", roll: 0.3 },
      { k: "S", len: 245, env: "train", f: [{ t: "boost", at: 0.32 }, { t: "box", at: 0.76, n: 4 }] },
      { k: "T", ang: 120, r: 110, env: "roof", roll: -0.22 },
      { k: "S", len: 280, env: "runway", f: [{ t: "ramp", at: 0.82, h: 4, p: 32, boost: 1 }] },
      { k: "S", len: 170, env: "airport", f: [{ t: "boost", at: 0.52 }] },
    ],
    events: [{ t: "traffic", seg: 0, at: 0.15, len: 150, n: 4, speed: 24, dir: -1, type: "car" }, { t: "train", seg: 4, at: 0.5, period: 8, off: 2 }],
    lms: [{ kind: "skyline", seg: 2, at: 0.5, side: -1, off: 85 }],
  },
  // ---------------- Whiteout Ridge ----------------
  { id: "whiteout", name: "Whiteout Ridge", laps: 5, hw: 11, start: { h: 0 },
    theme: { sky: SKY.alp, ground: 0xc9dce8, groundTex: "snow", fogFar: 1150, mtns: [18, 0x7897ad, false] },
    segs: [
      { k: "S", len: 190, env: "pass", f: [{ t: "box", at: 0.62, n: 4 }] },
      { k: "T", ang: 105, r: 46, env: "glacier", roll: 0.24 },
      { k: "S", len: 115, env: "glacier", f: [{ t: "boost", at: 0.36 }] },
      { k: "T", ang: -45, r: 36, env: "snow", roll: -0.3 },
      { k: "S", len: 155, env: "skijump", f: [{ t: "ramp", at: 0.72, h: 4, p: 31, boost: 1 }] },
      { k: "T", ang: 135, r: 38, env: "glacier", roll: 0.34 },
      { k: "S", len: 110, env: "pass", f: [{ t: "box", at: 0.45, n: 4 }] },
      { k: "T", ang: 75, r: 48, env: "mountain", roll: -0.22 },
      { k: "S", len: 125, env: "glacier", f: [{ t: "boost", at: 0.28 }] },
      { k: "T", ang: -35, r: 34, env: "snow" },
      { k: "S", len: 130, env: "mountain" },
      { k: "T", ang: 125, r: 44, env: "pass" },
      { k: "S", len: 145, env: "glacier", f: [{ t: "boost", at: 0.7 }] },
    ],
    events: [{ t: "avalanche", seg: 6, at: 0.3, len: 80, lap: 2, n: 6 }, { t: "boulder", seg: 2, at: 0.12, len: 85, n: 2, speed: 16 }],
    lms: [{ kind: "mountain", seg: 3, at: 0.5, side: 1, off: 48 }, { kind: "forest", seg: 8, at: 0.5, side: -1, off: 40 }],
  },
  // ---------------- HyperCoaster ----------------
  { id: "hypercoaster", name: "HyperCoaster", laps: 5, hw: 12, start: { h: 0 },
    theme: { sky: SKY.dusk, ground: 0x253448, fogFar: 1500 },
    segs: [
      { k: "S", len: 185, env: "coaster", dy: 82, ease: 1, f: [{ t: "boost", at: 0.18 }, { t: "box", at: 0.72, n: 4 }] },
      { k: "T", ang: 140, r: 42, env: "coaster", roll: 0.42 },
      { k: "S", len: 105, env: "coaster", dy: -82, ease: 1, f: [{ t: "boost", at: 0.52 }] },
      { k: "LOOP", r: 17, env: "coaster" },
      { k: "S", len: 125, env: "coaster", cork: 1, fixed: 1, f: [{ t: "box", at: 0.52, n: 3 }] },
      { k: "T", ang: 35, r: 38, env: "coaster", roll: -0.42 },
      { k: "S", len: 145, env: "coaster", dy: 30, ease: 1, f: [{ t: "ramp", at: 0.78, h: 3.5, p: 30, boost: 1 }] },
      { k: "T", ang: 155, r: 40, env: "coaster", roll: 0.48 },
      { k: "S", len: 105, env: "coaster", dy: -30, ease: 1, f: [{ t: "boost", at: 0.36 }] },
      { k: "T", ang: 70, r: 48, env: "coaster", roll: -0.35 },
      { k: "S", len: 160, env: "coaster", f: [{ t: "boost", at: 0.72 }] },
      { k: "T", ang: -40, r: 34, env: "coaster", roll: 0.3 },
      { k: "S", len: 115, env: "coaster" },
    ],
    events: [{ t: "rotor", seg: 1, at: 0.52, r: 8, speed: 1.6 }],
    lms: [{ kind: "coaster", seg: 7, at: 0.5, side: -1, off: 36 }],
  },
  // ---------------- Feralwood Rally ----------------
  { id: "feralwood", name: "Feralwood Rally", hw: 12, start: { h: 0 },
    theme: { sky: SKY.day, ground: 0x31502f, groundTex: "forest", fogFar: 1000, mtns: [12, 0x28442d, false] },
    segs: [
      { k: "S", len: 150, env: "forest", dy: 100, ease: 1, f: [{ t: "obst", at: 0.42, kind: "tree", n: 3, spread: 14 }, { t: "box", at: 0.78, n: 4 }] },
      { k: "T", ang: 125, r: 45, env: "mudtrail" },
      { k: "S", len: 95, env: "dirt", dy: -170, ease: 1, f: [{ t: "obst", at: 0.5, kind: "rock", n: 4, spread: 16 }, { t: "boost", at: 0.83 }] },
      { k: "T", ang: -55, r: 32, env: "forest", roll: 0.25 },
      { k: "S", len: 135, env: "scaffold", hw: 3.8, wallL: null, wallR: null, f: [{ t: "gap", at: 0.7, len: 14, ramp: 1, p: 24 }] },
      { k: "T", ang: 145, r: 38, env: "river" },
      { k: "S", len: 110, env: "mudtrail", dy: 70, ease: 1, f: [{ t: "box", at: 0.35, n: 4 }, { t: "ramp", at: 0.82, h: 3.2, p: 28 }] },
      { k: "T", ang: 75, r: 50, env: "rally" },
      { k: "S", len: 95, env: "forest", f: [{ t: "boost", at: 0.46 }] },
      { k: "T", ang: -35, r: 30, env: "mudtrail" },
      { k: "S", len: 120, env: "river", f: [{ t: "box", at: 0.6, n: 4 }] },
      { k: "T", ang: 70, r: 42, env: "forest" },
      { k: "S", len: 130, env: "rally" },
      { k: "T", ang: 35, r: 52, env: "mudtrail" },
      { k: "S", len: 100, env: "forest" },
    ],
    events: [{ t: "boulder", seg: 2, at: 0.15, len: 110, n: 3, speed: 17 }, { t: "traffic", seg: 6, at: 0.2, len: 110, n: 2, speed: 8, kind: "cow" }, { t: "debris", seg: 0, at: 0.62, len: 70, n: 6, lap: 2, c: 0x684827 }],
    lms: [{ kind: "forest", seg: 0, at: 0.5, side: 1, off: 48 }, { kind: "chalet", seg: 7, at: 0.5, side: -1, off: 34 }],
  },
  // ---------------- Brewery Basement ----------------
  { id: "brewerybasement", name: "Brewery Basement", hw: 10, start: { h: 0 },
    theme: { sky: SKY.night, ground: 0x40434b, groundTex: "city", fogFar: 900 },
    segs: [
      { k: "S", len: 130, env: "barn", f: [{ t: "box", at: 0.55, n: 4 }, { t: "obst", at: 0.82, kind: "barrel", n: 3, spread: 12 }] },
      { k: "T", ang: 150, r: 35, env: "hall" },
      { k: "S", len: 90, env: "warehouse", f: [{ t: "obst", at: 0.45, kind: "crate", n: 4, spread: 12 }] },
      { k: "T", ang: -60, r: 30, env: "tunnel" },
      { k: "S", len: 105, env: "foodcourt", f: [{ t: "box", at: 0.5, n: 4 }] },
      { k: "T", ang: 135, r: 36, env: "store" },
      { k: "S", len: 85, env: "lobby", f: [{ t: "boost", at: 0.34 }, { t: "box", at: 0.74, n: 4 }] },
      { k: "T", ang: 45, r: 44, env: "garage" },
      { k: "S", len: 100, env: "barn", f: [{ t: "ramp", at: 0.75, h: 2.8, p: 25 }] },
      { k: "T", ang: 100, r: 35, env: "tunnel" },
      { k: "S", len: 100, env: "warehouse", f: [{ t: "obst", at: 0.35, kind: "barrel", n: 4, spread: 14 }] },
      { k: "T", ang: -10, r: 50, env: "hall" },
      { k: "S", len: 90, env: "lobby" },
    ],
    events: [{ t: "crusher", seg: 2, at: 0.55 }, { t: "swing", seg: 5, at: 0.5, r: 8, kind: "axe", speed: 1.5 }, { t: "rotor", seg: 7, at: 0.35, r: 7, speed: 1.35 }],
    lms: [],
  },
  // ---------------- Clocktower Interior ----------------
  { id: "clocktowerinterior", name: "Clocktower Interior", hw: 10, start: { h: 0 },
    theme: { sky: SKY.dusk, ground: 0x443d4c, groundTex: "stone", fogFar: 850 },
    segs: [
      { k: "S", len: 145, env: "cathedral", f: [{ t: "box", at: 0.62, n: 4 }] },
      { k: "T", ang: 135, r: 34, env: "hall" },
      { k: "S", len: 100, env: "hallway", f: [{ t: "boost", at: 0.58 }] },
      { k: "T", ang: 45, r: 30, env: "lobby" },
      { k: "LIFT", h: 110, env: "elevator", speed: 24 },
      { k: "S", len: 125, env: "stairs", dy: -110, ease: 1, f: [{ t: "ramp", at: 0.74, h: 3, p: 26 }] },
      { k: "T", ang: 160, r: 36, env: "terminal" },
      { k: "S", len: 95, env: "store", f: [{ t: "obst", at: 0.45, kind: "crate", n: 3, spread: 12 }, { t: "box", at: 0.78, n: 4 }] },
      { k: "T", ang: -40, r: 32, env: "tunnel" },
      { k: "S", len: 110, env: "cathedral", f: [{ t: "boost", at: 0.35 }] },
      { k: "T", ang: 100, r: 40, env: "hallway" },
      { k: "S", len: 105, env: "stairs" },
      { k: "T", ang: -40, r: 34, env: "lobby" },
      { k: "S", len: 100, env: "cathedral" },
    ],
    events: [{ t: "crusher", seg: 5, at: 0.5 }, { t: "collapse", seg: 7, at: 0.55, len: 18, lap: 2, sign: "CLOCKWORK FLOOR!" }],
    lms: [],
  },
  // ---------------- Cloudline Viaduct ----------------
  { id: "cloudline", name: "Cloudline Viaduct", hw: 12, start: { h: 0 },
    theme: { sky: SKY.night, ground: 0x192a42, groundTex: "city", fogFar: 1450 },
    segs: [
      { k: "S", len: 170, env: "sky", f: [{ t: "boost", at: 0.25 }, { t: "box", at: 0.72, n: 4 }] },
      { k: "T", ang: 165, r: 50, env: "skyglass", roll: 0.28 },
      { k: "S", len: 185, env: "scaffold", hw: 3.8, wallL: null, wallR: null, fixed: 1, f: [{ t: "gap", at: 0.63, len: 15, ramp: 1, p: 26 }] },
      { k: "T", ang: -55, r: 34, env: "roof", roll: -0.3 },
      { k: "S", len: 145, env: "skybridge", f: [{ t: "box", at: 0.55, n: 4 }] },
      { k: "T", ang: 135, r: 44, env: "sky", roll: 0.32 },
      { k: "S", len: 165, env: "skyglass", f: [{ t: "boost", at: 0.4 }, { t: "ramp", at: 0.82, h: 4, p: 30 }] },
      { k: "T", ang: 40, r: 60, env: "autobahn" },
      { k: "S", len: 125, env: "roof", f: [{ t: "box", at: 0.52, n: 4 }] },
      { k: "T", ang: 110, r: 38, env: "sky" },
      { k: "S", len: 150, env: "skyglass" },
      { k: "T", ang: -35, r: 42, env: "skybridge" },
      { k: "S", len: 135, env: "sky" },
    ],
    events: [{ t: "traffic", seg: 4, at: 0.15, len: 100, n: 3, speed: 13, type: "car" }, { t: "rotor", seg: 7, at: 0.45, r: 8, speed: 1.35 }],
    lms: [{ kind: "skyline", seg: 2, at: 0.5, side: 1, off: 70 }],
  },
  // ---------------- Crevasse Run ----------------
  { id: "crevasserun", name: "Crevasse Run", hw: 11, start: { h: 0 },
    theme: { sky: SKY.alp, ground: 0xabc4d4, groundTex: "snow", fogFar: 1000, mtns: [18, 0x7795aa, false] },
    segs: [
      { k: "S", len: 160, env: "pass", dy: 95, ease: 1, f: [{ t: "box", at: 0.65, n: 4 }] },
      { k: "T", ang: 115, r: 42, env: "glacier", roll: 0.3 },
      { k: "S", len: 145, env: "glacier", hw: 3.8, sh: null, shw: 0, wallL: null, wallR: null, fixed: 1, dy: -180, ease: 1, f: [{ t: "boost", at: 0.35 }, { t: "gap", at: 0.78, len: 17, ramp: 1, p: 27 }] },
      { k: "T", ang: -35, r: 32, env: "skijump" },
      { k: "S", len: 125, env: "snow", dy: 120, ease: 1, f: [{ t: "ramp", at: 0.72, h: 4.5, p: 32, boost: 1 }] },
      { k: "T", ang: 145, r: 38, env: "mountain", roll: -0.28 },
      { k: "S", len: 120, env: "pass", dy: -35, ease: 1, f: [{ t: "boost", at: 0.4 }] },
      { k: "T", ang: 55, r: 50, env: "glacier" },
      { k: "S", len: 130, env: "glacier", hw: 3.8, sh: null, shw: 0, wallL: null, wallR: null, fixed: 1, f: [{ t: "box", at: 0.55, n: 3 }] },
      { k: "T", ang: 105, r: 42, env: "snow" },
      { k: "S", len: 110, env: "mountain" },
      { k: "T", ang: -25, r: 32, env: "pass" },
      { k: "S", len: 145, env: "glacier", f: [{ t: "boost", at: 0.4 }] },
    ],
    events: [{ t: "avalanche", seg: 6, at: 0.24, len: 100, lap: 2, n: 7 }, { t: "boulder", seg: 4, at: 0.1, len: 90, n: 2, speed: 16 }],
    lms: [{ kind: "mountain", seg: 3, at: 0.5, side: 1, off: 52 }],
  },
  // ---------------- Thunderloop Skyway ----------------
  { id: "thunderloop", name: "Thunderloop Skyway", hw: 11, start: { h: 0 },
    theme: { sky: SKY.night, ground: 0x14182f, groundTex: "city", fogFar: 1350 },
    segs: [
      { k: "S", len: 180, env: "sky", f: [{ t: "boost", at: 0.2 }, { t: "box", at: 0.75, n: 4 }] },
      { k: "T", ang: 100, r: 42, env: "skyglass", roll: 0.52 },
      { k: "S", len: 100, env: "sky", cork: 1, fixed: 1, f: [{ t: "boost", at: 0.65 }] },
      { k: "T", ang: 20, r: 54, env: "sky", roll: -0.55 },
      { k: "S", len: 105, env: "sky" },
      { k: "T", ang: 120, r: 34, env: "coaster", roll: 0.4 },
      { k: "LOOP", r: 16, env: "coaster" },
      { k: "S", len: 160, env: "skyglass", hw: 3.7, wallL: null, wallR: null, fixed: 1, f: [{ t: "gap", at: 0.68, len: 16, ramp: 1, p: 28 }] },
      { k: "T", ang: 40, r: 50, env: "sky", roll: -0.4 },
      { k: "S", len: 135, env: "sky", f: [{ t: "ramp", at: 0.74, h: 4, p: 30, boost: 1 }] },
      { k: "T", ang: 115, r: 38, env: "skyglass", roll: -0.38 },
      { k: "S", len: 110, env: "sky", f: [{ t: "box", at: 0.5, n: 4 }, { t: "boost", at: 0.83 }] },
      { k: "T", ang: -35, r: 32, env: "sky" },
      { k: "S", len: 120, env: "skyglass" },
    ],
    events: [{ t: "rotor", seg: 5, at: 0.42, r: 8, speed: 1.8 }, { t: "collapse", seg: 7, at: 0.55, len: 18, lap: 2, sign: "SKYWAY FAILURE!" }],
    lms: [{ kind: "skyline", seg: 5, at: 0.5, side: 1, off: 72 }],
  },
];
export const CUPS = [
  { id: "brezel", name: "Pretzel Cup", icon: "🥨", tracks: ["berlin", "schwarzwald", "bauernhof", "kaufhaus", "moonlitmill", "feralwood"] },
  { id: "bier", name: "Stein Cup", icon: "🍺", tracks: ["wiesn", "hafen", "rhein", "nordsee", "stormglass", "brewerybasement"] },
  { id: "kuckuck", name: "Cuckoo Cup", icon: "🐦", tracks: ["koeln", "maerchen", "kanal", "platte", "dragonspire", "clocktowerinterior"] },
  { id: "autobahn", name: "Highway Cup", icon: "🚗", tracks: ["autobahn", "flughafen", "bahnhof", "baustelle", "slipstream", "cloudline"] },
  { id: "alpen", name: "Alpine Cup", icon: "🏔️", tracks: ["zugspitze", "schloss", "talsperre", "schanze", "whiteout", "crevasserun"] },
  { id: "meister", name: "Champions Cup", icon: "🏆", tracks: ["zeche", "skyline", "achterbahn", "nordschleife", "hypercoaster", "thunderloop"] },
];
export const TRACK = Object.fromEntries(TRACKS.map(t => [t.id, t]));
